version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    reviewers:
      - '@thnetii/organization'
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    reviewers:
      - '@thnetii/organization'
