name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  tsc:
    name: TypeScript check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: thnetii/gh-actions/src/add-matcher-npm@main
      - name: npm install
        run: npm ci -workspaces --include-workspace-root
      - name: npm run lint:tsc
        run: npm run lint:tsc

  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: thnetii/gh-actions/src/add-matcher-npm@main
      - name: npm install
        run: npm ci -workspaces --include-workspace-root
      - name: npm run lint:eslint
        run: npm run lint:eslint
