name: Code Validation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  nodejs:
    name: Node.js
    uses: thnetii/.github/.github/workflows/nodejs-code-validation.yml@main
    with:
      checkout-parameters: >
        {
          "submodules": true
        }
      npm-install-check-enable: true
      npm-install-arguments: >
        [
          "--workspaces",
          "--include-workspace-root"
        ]
      tsc-check-enable: true
      tsc-parameters: >
        {
          "arguments": "--noEmit\n-p\n./jsconfig.json"
        }
      eslint-check-enable: true
      prettier-check-enable: true
